[[CUTENSOR]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "6e2b77b3f4385f09b93d41018b88ef1445b5c464"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR.download]]
    sha256 = "f76ae5d4409ea9c61a7f8a76baca727505a4a6ffd58e6517253c56212a52758f"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_jll.jl/releases/download/CUTENSOR-v2.5.0+0/CUTENSOR.v2.5.0.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[CUTENSOR]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "sbsa"
git-tree-sha1 = "b3d2fddcc3e9aa6febe6c9fd40b1585c062f99fc"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR.download]]
    sha256 = "c24e5a58384d4eeae7ffb07d1674ca46af132df42a6ecf164d99a673dee82074"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_jll.jl/releases/download/CUTENSOR-v2.5.0+0/CUTENSOR.v2.5.0.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.0.tar.gz"
[[CUTENSOR]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "d32ecce7c56169edcb76513ad7c0e561241f5a36"
lazy = true
os = "windows"

    [[CUTENSOR.download]]
    sha256 = "ce10b4141c13007c21aac1080eac169ecabafafcbd957df19db3ac7ded8abe01"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_jll.jl/releases/download/CUTENSOR-v2.5.0+0/CUTENSOR.v2.5.0.x86_64-w64-mingw32-cuda+12.0.tar.gz"
[[CUTENSOR]]
arch = "x86_64"
cuda = "13.0"
git-tree-sha1 = "c0164b3257e6b2356615dd946f960cb7e7004145"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR.download]]
    sha256 = "245fdcfa40b272ed9846afba02bf4efc2b982f0ffc4b09df2d8f3234b35f8a70"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_jll.jl/releases/download/CUTENSOR-v2.5.0+0/CUTENSOR.v2.5.0.x86_64-linux-gnu-cuda+13.0.tar.gz"
[[CUTENSOR]]
arch = "aarch64"
cuda = "13.0"
git-tree-sha1 = "70869825dd11dd604c1ed0e15f8bb1b674782279"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR.download]]
    sha256 = "ee8c15926289046cbb4cf49a58c836eaee459309f854b942f991969e87fe8c1d"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_jll.jl/releases/download/CUTENSOR-v2.5.0+0/CUTENSOR.v2.5.0.aarch64-linux-gnu-cuda+13.0.tar.gz"
[[CUTENSOR]]
arch = "x86_64"
cuda = "13.0"
git-tree-sha1 = "51d5fb8bf2e3418d5964e7c54806189828ff6766"
lazy = true
os = "windows"

    [[CUTENSOR.download]]
    sha256 = "4cbc015c4ddc683b373de403f7daf77fa0103ed27ab57404b7bd9078efb00e99"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_jll.jl/releases/download/CUTENSOR-v2.5.0+0/CUTENSOR.v2.5.0.x86_64-w64-mingw32-cuda+13.0.tar.gz"
