[[CUTENSOR]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "47a56ad2892e1fcc6f1c8158de9f25f089bbc327"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR.download]]
    sha256 = "0d8ba8314bb44fa9e9bf5bbfdb684cd17306c88a764fadd66f70aabff342080f"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_jll.jl/releases/download/CUTENSOR-v2.8.1+0/CUTENSOR.v2.8.1.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[CUTENSOR]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "sbsa"
git-tree-sha1 = "9d505d9b32eb9f91a1d3e2951063c4e520f59d0b"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR.download]]
    sha256 = "d905f806332e16b8788595bba26e06a76e61d4414a87269376ae0b53d6639f14"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_jll.jl/releases/download/CUTENSOR-v2.8.1+0/CUTENSOR.v2.8.1.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.0.tar.gz"
[[CUTENSOR]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "8ffad14b6283cfaaf6edca6d865456d890e4c969"
lazy = true
os = "windows"

    [[CUTENSOR.download]]
    sha256 = "5842c269ee14ba43083c28285675c184bac4ffddc9c29f876d428528fc109ec8"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_jll.jl/releases/download/CUTENSOR-v2.8.1+0/CUTENSOR.v2.8.1.x86_64-w64-mingw32-cuda+12.0.tar.gz"
[[CUTENSOR]]
arch = "x86_64"
cuda = "13.0"
git-tree-sha1 = "22334324b0ed19f6387aa1f0d1fb691a44997729"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR.download]]
    sha256 = "7c0b7d1000b212bf297caf94b2f03f2f895887f0beaf8d1a4ec4602c426b7feb"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_jll.jl/releases/download/CUTENSOR-v2.8.1+0/CUTENSOR.v2.8.1.x86_64-linux-gnu-cuda+13.0.tar.gz"
[[CUTENSOR]]
arch = "aarch64"
cuda = "13.0"
git-tree-sha1 = "f55f089b675f60fd0c6c84c5abe8de7d77a196ac"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR.download]]
    sha256 = "75bcaf0ea400b3cc0ebacb163c47b5d866bb500122cfb892c7606da93bed4100"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_jll.jl/releases/download/CUTENSOR-v2.8.1+0/CUTENSOR.v2.8.1.aarch64-linux-gnu-cuda+13.0.tar.gz"
[[CUTENSOR]]
arch = "x86_64"
cuda = "13.0"
git-tree-sha1 = "35250602571d46ad582a1b6fe36ea4275e293694"
lazy = true
os = "windows"

    [[CUTENSOR.download]]
    sha256 = "76f0158103f8ec835e7cab00be94be63176021d4c0c18b1cdc21f056e91b8c10"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_jll.jl/releases/download/CUTENSOR-v2.8.1+0/CUTENSOR.v2.8.1.x86_64-w64-mingw32-cuda+13.0.tar.gz"
